export const enUS = {
  ABOUT_ME: 'About me',
  PORTFOLIO: 'Portfolio',
  LOGOUT: 'Logout',
  HI: 'Hi, ',
  DESCRIPTION: 'Hi, I\'m Jason, a frontend engineer...',
  BACHELOR: 'Bachelor: Computer Science, NKFUST. 2004/9 - 2008/6',
  MASTER: 'Master: Computer Science, NKFUST. 2013/9 - 2015/7',
  EDUCATION: 'Education',
  EXPERIENCE: 'Experience',
  EXPERIENCE_1: 'Assistant Engineer, FUTABA. 2010/7 - 2011/10',
  EXPERIENCE_2: 'Assistant Engineer, NKUHT. 2011/10 - 2015/10',
  EXPERIENCE_3: 'Engineer, Wistron. 2015/10 - Present',
  SKILLS: 'Skills',
  SKILLS_1: 'Frontend development：ReactJS, CSS, HTML',
  SKILLS_2: 'Backend development：Web API(C#)',
  MOTTO: 'Motto',
  MOTTO_1: 'Practice makes perfect',
  CONTACT: 'Contact',
  CONTACT_1: 'Email-Address: jasonyen2008@gmail.com',
  BADGE: 'Badge'
};
