export const zhTW = {
  ABOUT_ME: '關於我',
  PORTFOLIO: '範例集',
  LOGOUT: '登出',
  HI: '嗨，',
  DESCRIPTION: '您好，我是張俊彥，是一位程式設計師...',
  BACHELOR: '學士: 國立高雄第一科技大學 電腦與通訊工程系 2004/9 - 2008/6',
  MASTER: '碩士: 國立高雄第一科技大學 電腦與通訊工程所 2013/9 - 2015/7',
  EDUCATION: '教育',
  EXPERIENCE: '經歷',
  EXPERIENCE_1: '台灣雙葉電子 助理工程師 2010/7 - 2011/10',
  EXPERIENCE_2: '高雄餐旅大學 助理工程師 2011/10 - 2015/10',
  EXPERIENCE_3: '緯創資通 工程師 2015/10 - 仍在職',
  SKILLS: '專長',
  SKILLS_1: '前端開發：ReactJS, CSS, HTML',
  SKILLS_2: '後端開發：Web API(C#)',
  MOTTO: '座右銘',
  MOTTO_1: '勤能補拙',
  CONTACT: '聯絡方式',
  CONTACT_1: '電子郵件: jasonyen2008@gmail.com'
};
